### ISSUE TITLE
Cannot install with npm install

### ISSUE THREAD

**Issue by mattstratton** [gethinode/netlify-plugin-dartsass#1]
When I try to run `npm install -D netlify-plugin-dartsass `, I get the following error:
```
npm ERR! code ENOVERSIONS
npm ERR! No versions available for netlify-plugin-dartsass
```

Same issue occurs if I manually add to `package.json` and then try to run a netlify build :)

**Comment by markdumay** [comment]
The readme was missing the scope, the correct command should be:

```bash
npm install -D @gethinode/netlify-plugin-dartsass
```

I've revised the instructions.

**Comment by mattstratton** [comment]
That got it past that part! I did find that it has to also be listed this well in `netlify.toml` so I opened #4 for that doc update too!

**Comment by markdumay** [comment]
Thanks, it has been merged!
